FROM golang:1.17

RUN apt-get update

RUN apt-get install -y \
    wget lsb-release

RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update

RUN apt-get -y install postgresql

# COPY ./postgresql.service /etc/systemd/system/postgresql.service

# RUN systemctl enable postgresql

RUN update-rc.d postgresql defaults

EXPOSE 8080

ENTRYPOINT [ "/bin/bash" ]